name: SPACE Project CI
on:
  # Workflow will be triggered when code is pushed to one of the branches below
  push:
    branches: ["master"]
  # Workflow will be triggered when there is a pull request on master branch
  pull_request:
    branches: ["master"]
# this job will be run when either one of the above trigger is detected
jobs:
  build:
    # This is the env that all the below steps will run inside of
    # & by default the create react app test scripts run in CI and it disables watch mode 
    env:
      CI: true
    strategy:
      matrix: 
        node-version: [14.x, 16.x]
    # runtime env for our CI pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --prefix client
      - run: npm test
